# Generated by Django 5.1.2 on 2024-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('cells', models.PositiveIntegerField()),
                ('security_level', models.CharField(choices=[('Low', 'Low Security'), ('Mid', 'Mid Security'), ('High', 'High Security')], max_length=10)),
            ],
        ),
    ]
