# Generated by Django 5.1.3 on 2024-11-28 22:19

import django.core.validators
import django.db.models.deletion
import theProject2.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalMainInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2)])),
                ('middle_name', models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=35)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.PositiveIntegerField(validators=[theProject2.utils.validators.AgeLimitValidator()])),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('main_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_info', to='criminals.criminalmaininfo')),
            ],
        ),
    ]
