# Generated by Django 5.1.2 on 2024-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0002_criminalmaininfo_policeman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminalmaininfo',
            options={'permissions': [('can_approve_criminals', 'Can approve criminals')]},
        ),
        migrations.AddField(
            model_name='criminaldetailinfo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='criminalmaininfo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='criminalmaininfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
