# Generated by Django 5.1.2 on 2024-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0007_alter_criminalmaininfo_policeman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='eye_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='hair_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criminaldetailinfo',
            name='race',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
