# Generated by Django 5.1.2 on 2024-12-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminals', '0008_alter_criminaldetailinfo_address_and_more'),
        ('prisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalmaininfo',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criminals', to='prisons.prison'),
        ),
    ]
